<div class="flex justify-between items-baseline">
    <div>
        <p class="uppercase text-2xl text-dark font-medium"> <strong>{{ Route::currentRouteName() }}</strong></p>
    </div>
    <div class="flex justify-center">
        <div>
          <div class="dropdown relative">
            <a
              class="
                dropdown-toggle
                border
                px-2
                py-1
                rounded-full
                shadow-md
                hover:shadow-lg
                transition
                duration-150
                ease-in-out
              "
              href="#"
              type="button"
              id="dropdownMenuButton2"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
                <i class="bi bi-person-fill text-dark font-medium text-xl"></i>
            </a>
            <ul
              class="
                dropdown-menu
                min-w-max
                absolute
                bg-white
                text-base
                z-50
                float-left
                py-2
                list-none
                text-left
                rounded-lg
                shadow-lg
                mt-1
                hidden
                m-0
                bg-clip-padding
                border-none
              "
              aria-labelledby="dropdownMenuButton2"
            >
              <li>
                <a
                  class="
                    dropdown-item
                    text-sm
                    py-2
                    px-4
                    font-normal
                    block
                    w-full
                    whitespace-nowrap
                    bg-transparent
                    text-gray-700
                    hover:bg-gray-100
                  "
                  href="#"
                  >Logout</a
                >
              </li>
            </ul>
          </div>
        </div>
      </div>
</div>